In [1]:
#1. Importa el paquete NUMPY bajo el nombre np.
import numpy as np

In [5]:
#2. Imprime la versión de NUMPY y la configuración.
print(np.__version__)

1.26.4


In [19]:
#3. Genera un array tridimensional de 2x3x5 con valores aleatorios. Asigna el array a la variable "a"
# Desafío: hay al menos tres maneras fáciles que usan numpy para generar arrays aleatorios. ¿Cuántas formas puedes encontrar?

import random

a = np.random.randint(3, size=(2, 3, 5))


In [21]:
#4. Imprime a.
print(a)

[[[0 1 2 2 1]
  [2 1 2 2 2]
  [0 1 0 0 0]]

 [[2 1 0 0 1]
  [1 1 0 0 2]
  [1 1 2 0 2]]]


In [29]:
#5. Crea un array tridimensional de 5x2x3 con todos los valores igual a 1.
#Asigna el array a la variable "b"

b = np.ones((5,2,3))

In [31]:
#6. Imprime b
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [35]:
#7. ¿Tienen a y b el mismo tamaño? ¿Cómo lo demuestras en código Python?




SyntaxError: invalid syntax (3817924507.py, line 2)

In [ ]:
#8. ¿Es posible sumar a y b? ¿Por qué sí o por qué no?
No, La suma de matrices en numpy requiere que las matrices tengan las mismas dimensiones en cada eje.

In [41]:
#9. Transpone b para que tenga la misma estructura que a (es decir, se convierta en un array de 2x3x5). Asigna el array transpuesto a la variable "c".
c = np.transpose(b, axes=(1, 2, 0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [47]:
#10. Intenta sumar a y c. Ahora debería funcionar. Asigna la suma a la variable "d". Pero, ¿por qué funciona ahora?

d = a + c #Funciona porque ambas matrices tienen las mismas dimensiones (2,3,5)
print(d)

[[[1. 2. 3. 3. 2.]
  [3. 2. 3. 3. 3.]
  [1. 2. 1. 1. 1.]]

 [[3. 2. 1. 1. 2.]
  [2. 2. 1. 1. 3.]
  [2. 2. 3. 1. 3.]]]


In [51]:
#11. Imprime a y d. ¿Notas la diferencia y la relación entre los dos arrays en términos de los valores? Explica.

print(a)
print(d)
"""Como d es la suma entre a y c y c era compuesta de numeros 1, la d tiene 1 incrementado en los valores. 
Ademas ahora los valores aparecen con un punto."""

[[[0 1 2 2 1]
  [2 1 2 2 2]
  [0 1 0 0 0]]

 [[2 1 0 0 1]
  [1 1 0 0 2]
  [1 1 2 0 2]]]
[[[1. 2. 3. 3. 2.]
  [3. 2. 3. 3. 3.]
  [1. 2. 1. 1. 1.]]

 [[3. 2. 1. 1. 2.]
  [2. 2. 1. 1. 3.]
  [2. 2. 3. 1. 3.]]]


In [55]:
#12. Multiplica a y c. Asigna el resultado a e.
e = a * c
print(e)

[[[0. 1. 2. 2. 1.]
  [2. 1. 2. 2. 2.]
  [0. 1. 0. 0. 0.]]

 [[2. 1. 0. 0. 1.]
  [1. 1. 0. 0. 2.]
  [1. 1. 2. 0. 2.]]]


In [57]:
#13. ¿Es e igual a a? ¿Por qué sí o por qué no?
print(a)
"""Si, son iguales. Esto pasa porque los valores de c son 1 y cualquier numero de la a multiplcado por 1 va volver ele mismo. 
La unica diferencia es que ahora hay un '.' """


[[[0 1 2 2 1]
  [2 1 2 2 2]
  [0 1 0 0 0]]

 [[2 1 0 0 1]
  [1 1 0 0 2]
  [1 1 2 0 2]]]


In [63]:
#14. Identifica los valores máximos, mínimos y medios en d. Asigna esos valores a las variables "d_max", "d_min" y "d_mean"

d_max = np.max(d)

d_min = np.min(d)

d_mean = np.mean(d)
print(f"El valor máximo de 'd' es {d_max}")
print(f"El valor minimo de 'd' es {d_min}")
print(f"El valor medio de 'd' es {d_mean}")

El valor máximo de 'd' es 3.0
El valor minimo de 'd' es 1.0
El valor medio de 'd' es 2.0


In [ ]:
#15. Ahora queremos etiquetar los valores en d. Primero crea un array vacío "f" con la misma forma (es decir, 2x3x5) que d usando `np.empty`.

f = np.empty((2,3,5))

In [ ]:
"""
#16. Rellena los valores en f. Para cada valor en d, si es mayor que d_min pero menor que d_mean, asigna 25 al valor correspondiente en f.
Si un valor en d es mayor que d_mean pero menor que d_max, asigna 75 al valor correspondiente en f.
Si un valor es igual a d_mean, asigna 50 al valor correspondiente en f.
Asigna 0 al valor correspondiente(s) en f para d_min en d.
Asigna 100 al valor correspondiente(s) en f para d_max en d.
Al final, f debería tener solo los siguientes valores: 0, 25, 50, 75 y 100.
Nota: no necesitas usar Numpy en esta pregunta.
"""

In [ ]:
f[(d > d_min) & (d < d_mean)] = 25
print(f)

In [ ]:
f[(d > d_mean) & (d < d_max)] = 75
print(f)

In [ ]:
f[(d == d_mean)] = 50
print(f)

In [ ]:
f[(d == d_min)] = 0
print(f)

In [ ]:
f[(d == d_max)] = 100
print(f)

In [ ]:
#17. Imprime d y f. ¿Tienes el f esperado?
print(d)
print(f) Si, el f esta con los valores actualizados de 0 a 100.

In [ ]:
"""#17. Imprime d y f. ¿Tienes el f esperado?
Por ejemplo, si tu d es:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])"""

In [ ]:
f[d == d_min] = 'A'
f[(d > d_min) & (d < d_mean)] = 'B'
f[d == d_mean] = 'C'
f[(d > d_mean) & (d < d_max)] = 'D'
f[d == d_max] = 'E'